stages:
  - build

default:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build-api:
  stage: build
  image: docker
  services: 
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/api -f SmartMirrorHubV6.Api/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/api

build-updater:
  stage: build
  image: docker
  services: 
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/updater -f SmartMirrorHubV6.Updater/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/updater

build-website:
  stage: build
  image: docker
  services: 
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/website -f SmartMirrorHubV6.Website/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/website

build-tp-link-scraper:
  stage: build
  image: docker
  services: 
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/tp-link-scraper -f SmartMirrorHubV6.Dockers/TpLinkDecoScraper/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE_tp-link-scraper